INSERT INTO Products (Name,Brand,Category,Price,Description,ImageFileName,CreatedAt)
 VALUES
('Realme 7i', 'Realme', 'Smartphone', 7250.00, 'Budget-friendly smartphone with a large battery.', 'realme_7i.jpg',GETDATE()),
('Realme 6', 'Realme', 'Smartphone', 8300.00, 'Mid-range smartphone with a quad-camera setup.', 'realme_6.jpg',GETDATE()),
('Realme 9i', 'Realme', 'Smartphone', 9350.00, 'Mid-range smartphone with a high refresh rate display.', 'realme_9i.jpg',GETDATE()),
('Realme C21y', 'Realme', 'Smartphone', 5550.00, 'Entry-level smartphone with a large screen.', 'realme_c21y.jpg',GETDATE()),
('iPhone 15', 'Apple', 'Smartphone', 8000.00, 'The latest iPhone model with advanced features.', 'iphone15.jpg',GETDATE()),
('Galaxy S24', 'Samsung', 'Smartphone', 7900.00, 'A high-performance Android smartphone.', 'galaxy_s24.jpg',GETDATE()),
('MacBook Pro', 'Apple', 'Laptop', 22000.00, 'Powerful laptop for professionals.', 'macbook_pro.jpg',GETDATE()),
('Dell XPS 13', 'Dell', 'Laptop', 15500.00, 'Lightweight and portable laptop.', 'dell_xps_13.jpg',GETDATE()),
('Apple Watch Series 8', 'Apple', 'Wearables', 5400.00, 'Smartwatch with advanced features.', 'apple_watch_series_8.jpg',GETDATE()),
('Samsung Galaxy Watch 5', 'Samsung', 'Wearables', 7350.00, 'Android-compatible smartwatch.', 'galaxy_watch_5.jpg',GETDATE()),
('Sony Bravia TV', 'Sony', 'Electronics', 11800.00, 'High-definition television with smart features.', 'sony_bravia_tv.jpg',GETDATE()),
('LG OLED TV', 'LG', 'Electronics', 11500.00, 'Premium OLED television with excellent picture quality.', 'lg_oled_tv.jpg',GETDATE()),
('Samsung Galaxy Tab S9', 'Samsung', 'Tablet', 14800.00, 'Android tablet with a large display.', 'galaxy_tab_s9.jpg',GETDATE()),
('OPPO Find X6 Pro', 'OPPO', 'Smartphone', 11000.00, 'Flagship smartphone with advanced camera system.', 'oppo_find_x6_pro.jpg',GETDATE()),
('Huawei P60 Pro', 'Huawei', 'Smartphone', 8900.00, 'High-performance smartphone with Kirin processor.', 'huawei_p60_pro.jpg',GETDATE()),
('Realme GT Neo 5', 'Realme', 'Smartphone', 9500.00, 'Mid-range smartphone with fast charging.', 'realme_gt_neo_5.jpg',GETDATE()),
('HP Spectre x360', 'HP', 'Laptop', 16500.00, 'Premium convertible laptop with 360-degree hinge.', 'hp_spectre_x360.jpg',GETDATE()),
('Lenovo ThinkPad X1 Carbon', 'Lenovo', 'Laptop', 12000.00, 'Business-oriented laptop with durability and performance.', 'lenovo_thinkpad_x1_carbon.jpg',GETDATE()),
('OPPO Reno 8 Pro', 'OPPO', 'Smartphone', 10700.00, 'Mid-range smartphone with good camera performance.', 'oppo_reno_8_pro.jpg',GETDATE()),
('Huawei Mate 50 Pro', 'Huawei', 'Smartphone', 9200.00, 'High-end smartphone with advanced features.', 'huawei_mate_50_pro.jpg',GETDATE()),
('Realme 11 Pro+', 'Realme', 'Smartphone', 11400.00, 'Budget-friendly smartphone with decent specs.', 'realme_11_pro_plus.jpg',GETDATE()),
('HP Pavilion Aero 13', 'HP', 'Laptop', 15800.00, 'Lightweight and affordable laptop.', 'hp_pavilion_aero_13.jpg',GETDATE()),
('OPPO A78', 'OPPO', 'Smartphone', 9300.00, 'Entry-level smartphone with long battery life.', 'oppo_a78.jpg',GETDATE()),
('Huawei Nova 10 Pro', 'Huawei', 'Smartphone', 8600.00, 'Mid-range smartphone with curved display.', 'huawei_nova_10_pro.jpg',GETDATE()),
('Realme C55', 'Realme', 'Smartphone', 6200.00, 'Budget-friendly smartphone with basic features.', 'realme_c55.jpg',GETDATE()),
('HP Envy x360', 'HP', 'Laptop', 14000.00, 'Convertible laptop with good performance.', 'hp_envy_x360.jpg',GETDATE()),
('Lenovo Yoga 7i', 'Lenovo', 'Laptop', 15200.00, 'Convertible laptop with powerful processor.', 'lenovo_yoga_7i.jpg',GETDATE()),
('LG OLED Evo Gallery Series', 'LG', 'Smart TVs', 14400.00, 'Premium OLED TV with a minimalist design.', 'lg_oled_evo_gallery_series.jpg',GETDATE()),
('Realme GT Neo 3', 'Realme', 'Smartphone', 9500.00, 'High-performance smartphone with fast charging.', 'realme_gt_neo_3.jpg',GETDATE()),
('POCO F5 Pro', 'POCO', 'Smartphone', 9400.00, 'Mid-range smartphone with a powerful processor.', 'poco_f5_pro.jpg',GETDATE());